#!/bin/sh
# pre-commit hook: 每次提交自动递增 PATCH 版本号
# 大版本/小版本更新请手动修改 zimu_app/qt_app.py 中的 VERSION

VERSION_FILE="zimu_app/qt_app.py"

CURRENT_VERSION=$(grep '^VERSION = "' "$VERSION_FILE" | sed 's/^VERSION = "//;s/"$//')

if [ -z "$CURRENT_VERSION" ]; then
    echo "pre-commit: 无法在 $VERSION_FILE 中找到 VERSION，跳过版本递增"
    exit 0
fi

MAJOR=$(echo "$CURRENT_VERSION" | cut -d. -f1)
MINOR=$(echo "$CURRENT_VERSION" | cut -d. -f2)
PATCH=$(echo "$CURRENT_VERSION" | cut -d. -f3)
NEW_PATCH=$((PATCH + 1))

sed -i "s/^VERSION = \".*\"/VERSION = \"$MAJOR.$MINOR.$NEW_PATCH\"/" "$VERSION_FILE"
git add "$VERSION_FILE"
